name = "Intro"
uuid = "27d684bd-7c89-418b-b2df-4d8aff85963c"
authors = ["Anton Oresten"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1"
julia = "1.10"
